// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loghaqicaofnsmwpofix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvZ2hhcWljYW9mbnNtd3BvZml4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MDc5OTIsImV4cCI6MjA2NTI4Mzk5Mn0.NZJ2YOSdlaZbK5s5mGJm8QyhWZv7_Phq5NWvTDGtMwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);